#!/bin/bash

# ------
# This script runs on startup of the system.
# ------

# Default autostart commands. DO NOT REMOVE THIS.
"$ainadBaseDir/openbox/autostart.sh";

# ------
# You can place your custom autostart commands below.
#
# You can, also, create custom .sh or .desktop files inside ~/.config/autostart
# folder and they will also be executed on startup.
# ------
